INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Artifacter', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Army of Marionette', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('I''m so Happy【SP】', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('アストライアの双皿', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Anisakis -somatic mutation type "Forza"- 【SP】', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('妖隠し -あやかしかくし-', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('ARACHNE', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Arcanos', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('ALBIDA', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('∞=Inftrumental=', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('WICKeD CRφSS', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Water Horizon(BD MIX)', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('梅雪夜【SP】', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('ÆTHER', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('エキサイティング！！も・ちゃ・ちゃ☆', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Evans', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Elemental Creation', 'S', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Elemental Creation -GITADO ROCK Ver.-', 'A+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Erosion Mark', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Engraved Mark', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('EMPEROR OF THE AVALON', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('OVERHEAT -Type R-', 'B+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('御千手メディテーション', 'A+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('オタサー☆レボリューション', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('KHAMEN BREAK', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('GAIA', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('GAIA - GITADORA EDITION-', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Kailua', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Gimme a Big Beat(Hommarju Remix)', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('キャトられ❤️恋はモ～モク', 'B+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('狂喜宴舞', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('狂鬼村正', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Chirality', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Guilty Destruction', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('quaver♪', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('CLAMARE', 'S+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Ground Shake', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('GLITTER', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Glitch Nerds', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Cleopatrysm', 'B+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Chronoxia', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Gale Rider', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('CODE:1', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('黒点', 'B+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Cytokinesis', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Sakura Mirage', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('The 4th KAC DJ TOTTO''s SELECTION', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('THE FALLEN【SP】', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('The Least 100Sec', 'A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Genesis At Oasis', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('灼熱Beach Side Bunny', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('終焔のClaudia', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('シュレディンガーの猫', 'B+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('少年は空を辿る', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('JOMANDA', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('ZirkFied', 'A+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('XiNX', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Squeeze', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Stand Alone Beat Masta', 'A+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('STELLAR WIND', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('STULTI', 'A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('ストレイ・マーチ', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Snake Stick', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Snow Eagle', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('SPEED BLADE', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('ZZ', 'A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('双璧のVANESSA', 'B+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('DARK LEGACY', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('TITANS RETURN', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('太陽の子', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('打打打打打打打打打打【SP】', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('DOUBLE IMPACT', 'B+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Chinese Snowy Dance', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Chaplet', 'A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('256*256', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('December Breeze', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Daily Lunch Special', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Deus ex Machina', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('DEADLOCK', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('天空の夜明け', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('天地動伝説', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('True Blue', 'B+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('DRAGON KILLER', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('IX', 'S', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Nigra Ludia', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Nostalgia Is Lost', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('HYENA', 'B+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('HAERETICUS', 'S', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Bad Maniacs', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Valanga', 'B+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Hollywood Galaxy', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('VALLIS-NERIA', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('BEAT-NEW-WORLD', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Vairocana', 'A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('FIRE FIRE', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Poochie', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('fallen leaves', 'A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('fffff', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('FLOWER', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('FLOWER【SP】', 'B+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('プレインエイジア -PHQ remix-', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Playing With Fire', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('perditus†paradisus', 'A+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Broken', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Proluvies', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Benita', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('ほおずき程度には赤い頭髪', 'A+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('meme【SP】', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Miseria', 'A+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('見習い天使と星降りの丘', 'B+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('MEGANTO METEOR', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('雪月夜', 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Like+it!', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Regain Blue feat.せんざい（RoughSketch Remix）', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Lisa-RICCIA', 'A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('licca', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Refrain', 'B+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Liberation', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('龍と少女とデコヒーレンス', 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('量子の海のリントヴルム', 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('リリーゼと炎龍レーヴァテイン', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Ludus In Tenebris', 'B+', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('L''erisia(Primal Logic)【SP】', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('Red Goose', 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('海神', 'A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO songs (title, jiriki_rank, created_at, updated_at) VALUES ('WONDER WALKER', 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
